===============================================================================================================
-- (MAGNITUDE) MEASURE AND DIMESNIONS EXPLORATIONS
===============================================================================================================

--Find total customers by countries
SELECT COUNT(customer_key)as total_customers,country 
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC
-----------------------------------------------------------------------------------------------------------------
--Find total customers by gender
SELECT COUNT(gender)as total_customers,gender 
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC
-----------------------------------------------------------------------------------------------------------------
--Find total products by category
SELECT category,
COUNT(product_key) as total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC
-----------------------------------------------------------------------------------------------------------------
--What is the average costs in eachcategory?
select category,
avg(cost) as avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY category DESC
-----------------------------------------------------------------------------------------------------------------
--What is the total revenue generated for each category
SELECT dp.category,
SUM(fs.sales_amount) as total_revenue
FROM gold.fact_sales as fs
LEFT JOIN gold.dim_products as dp
ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY total_revenue DESC
-----------------------------------------------------------------------------------------------------------------
--Find the total revenue is generated by each customer
SELECT dc.customer_key,
dc.first_name, dc.last_name,
SUM(fs.sales_amount) as total_revenue
FROM gold.fact_sales as fs
LEFT JOIN gold.dim_customers as dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_key,dc.first_name, dc.last_name
ORDER BY total_revenue DESC
-----------------------------------------------------------------------------------------------------------------
--What is the distribution of sold items across countries?
SELECT dc.country,
SUM(fs.quantity) as total_sold_items
FROM gold.fact_sales as fs
LEFT JOIN gold.dim_customers as dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY total_sold_items DESC
-----------------------------------------------------------------------------------------------------------------
